spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/nar?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
        username: root
        password: 12345
        hikari:

          # Максимальное количество милисекунд, которое клиенты будут ждать для получения соединения,
          # прежде чем будет выброшено исключение
          connectionTimeout: 1000

          # Количество времени, через которое неактивное соединение убивается
          idle-timeout: 600000

          # Количество времени с момента создания соединения, через которое оно убивается.
          # Активные соединения убиваются после того, как их возвращают в пул
          max-lifetime: 1800000

          # Минимальное число неактивных соединений в пуле
          minimum-idle: 1

          # Тут понятно. Это максимальный размер пула
          maximum-pool-size: 5
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
        database: MYSQL
        #show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                
                # Названия таблиц и колонок через snake_case
                #physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                
                # Названия таблиц и колонок как в Java
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

application:
    images:
        directory: /opt/nar/images
